source 'https://rubygems.org'

gem 'nokogiri'
gem 'chronic'
gem 'httparty'
gem 'mechanize'
gem 'ruby-mp3info'
gem 'rack'
gem 'rack-contrib'
gem 'rack-cache'
gem 'puma'
gem 'sinatra', github: 'sinatra/sinatra'
gem 'parallel'
